version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: time-card-postgres
    environment:
      POSTGRES_DB: timecard
      POSTGRES_USER: timecard
      POSTGRES_PASSWORD: timecard123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timecard -d timecard"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
